chunk_size: 256
local_cpu: true
max_local_cpu_size: 4.0
remote_url: "priority-fs://?read_path=/home/junhaoy/ServerlessLMCache/.kvcache_remote&write_path=/home/junhaoy/ServerlessLMCache/.kvcache"
remote_serde: naive
use_layerwise: false
save_decode_cache: true
save_unfull_chunk: false
remote_storage_plugins: "priority_fs"
extra_config:
  remote_storage_plugin.priority_fs.module_path: embedded_demo.priority_fs_adapter
  remote_storage_plugin.priority_fs.class_name: PriorityFSConnectorAdapter
